"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import environ
from google.oauth2 import service_account

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    POSTGRES_DB=(str, "location_diary"),
    POSTGRES_USER=(str, "postgres"),
    POSTGRES_PASSWORD=(str),
    POSTGRES_HOST=(str, "127.0.0.1"),
    POSTGRES_PORT=(str, "5432"),
    GDAL_LIBRARY_PATH=(str),
    GEOS_LIBRARY_PATH=(str),
    GS_BUCKET_NAME=(str),
    GS_PROJECT_ID=(str),
    GS_CREDENTIALS_FILE=(str),
)
environ.Env.read_env(BASE_DIR.parent / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-it34=2)l6llp-8nfr((jx=7exkk5w2v4-ta$l7^k6dswh_ed-*"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# --- File storage: private Google Cloud Storage bucket, signed (expiring) URLs ---
# Media files never flow through Django; the API hands clients short-lived signed
# URLs and they read/write directly against GCS. The bucket must stay private.
GS_BUCKET_NAME = env("GS_BUCKET_NAME")
GS_PROJECT_ID = env("GS_PROJECT_ID")
_gs_credentials_file = env.str("GS_CREDENTIALS_FILE")
# Credentials are needed both to access objects AND to sign URLs locally.
# Resolve the path against the repo root (same base as .env) so it doesn't
# depend on the current working directory.
GS_CREDENTIALS = (
    service_account.Credentials.from_service_account_file(
        BASE_DIR.parent / _gs_credentials_file
    )
    if _gs_credentials_file
    else None
)
GS_DEFAULT_ACL = None  # objects inherit the bucket's (private) access; never public
GS_QUERYSTRING_AUTH = True  # .url returns a signed URL instead of a bare path
GS_EXPIRATION = timedelta(minutes=15)  # how long a signed URL stays valid
GS_FILE_OVERWRITE = False  # keep distinct uploads from clobbering each other

STORAGES = {
    # Default = media/user uploads -> GCS
    "default": {
        "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
    },
    # Static assets stay local for now
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "corsheaders",
    "rest_framework",
    "storages",
    "apps.users",
    "apps.location",
    "apps.events",
    "apps.media",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # CorsMiddleware must sit as high as possible (and before CommonMiddleware)
    # so it can attach CORS headers even on responses other middleware short-circuit.
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": env("POSTGRES_DB"),
        "USER": env("POSTGRES_USER"),
        "PASSWORD": env("POSTGRES_PASSWORD"),
        "HOST": env("POSTGRES_HOST"),
        "PORT": env("POSTGRES_PORT"),
    }
}


AUTH_USER_MODEL = "users.User"

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = ["apps.users.backends.EmailBackend"]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

GDAL_LIBRARY_PATH = env("GDAL_LIBRARY_PATH")
GEOS_LIBRARY_PATH = env("GEOS_LIBRARY_PATH")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

# --- SPA frontend: CORS, CSRF, and session cookies --------------------------
# The Vue app and this API are served same-site (e.g. app.example.com +
# api.example.com), so session-cookie auth works with SameSite=Lax. We keep
# every safety mechanism on — CSRF stays enforced, cookies are credentialed,
# and origins are allow-listed (never "*") — they're just made to work across
# the SPA's distinct origin.
#
# FRONTEND_ORIGINS is the allow-list of browser origins (scheme + host + port).
# Default covers Vite's dev server; override via env in prod, e.g.
#   FRONTEND_ORIGINS=https://app.example.com
FRONTEND_ORIGINS = env.list(
    "FRONTEND_ORIGINS",
    default=["http://localhost:5173", "http://127.0.0.1:5173"],
)

# CORS: allow the SPA's origin to call the API *with credentials* (cookies).
# Credentialed CORS forbids a wildcard origin, hence the explicit list.
CORS_ALLOWED_ORIGINS = FRONTEND_ORIGINS
CORS_ALLOW_CREDENTIALS = True

# CSRF: Django must trust the SPA's origin as a source of unsafe requests.
# (Separate from CORS — easy to forget. Needs the scheme on Django 4+.)
CSRF_TRUSTED_ORIGINS = FRONTEND_ORIGINS

# Cookies. SameSite=Lax is enough because the SPA and API are same-site; the
# browser still sends the session/CSRF cookies on the SPA's cross-origin XHR.
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
# The CSRF cookie must stay readable by JS so the SPA can echo it back in the
# X-CSRFToken header. The *session* cookie remains HttpOnly (Django default).
CSRF_COOKIE_HTTPONLY = False
# Secure cookies require HTTPS — on in production, off for local http dev.
# Defaults to the inverse of DEBUG; override with COOKIE_SECURE if needed.
SESSION_COOKIE_SECURE = env.bool("COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = env.bool("COOKIE_SECURE", default=not DEBUG)
