# Generated by Django 6.0.6 on 2026-06-14 23:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0002_alter_media_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
    ]
