# Generated by Django 6.0.6 on 2026-06-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventlocation",
            options={
                "ordering": [models.OrderBy(models.F("arrival"), nulls_last=True), "id"]
            },
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["-created_at"]},
        ),
    ]
